# Statement

After some discussion with Jörg about the best implementation of the symmetry functions it may pay to take a top-down view, and calculate the symmetry funcitons on a per-triple basis. Firstly, constructing the $r^2$ matrix implies that an $f_c(r^2)$ matrix can be computed and stored only once, reducing the frequency of computation drastically

In [1]:
using Distributed
@everywhere using SharedArrays
@everywhere using MachineLearningPotential
@everywhere using BenchmarkTools
@everywhere using StaticArrays

Loading the atomic parameters and symmetry functions

In [2]:
atoms = [[0.0000006584,       -0.0000019175,        0.0000000505],
[-0.0000005810,       -0.0000004871,        0.6678432175],
[0.1845874248,       -0.5681026047,        0.2986701538],
[-0.4832557457,       -0.3511072166,        0.2986684497],
[-0.4832557570,        0.3511046452,        0.2986669456],
[0.1845874064,        0.5681000550,        0.2986677202],
[0.5973371920,       -0.0000012681,        0.2986697030],
[-0.1845860897,       -0.5681038901,       -0.2986676192],
[-0.5973358752,       -0.0000025669,       -0.2986696020],
[-0.1845861081,        0.5680987696,       -0.2986700528],
[0.4832570624,        0.3511033815,       -0.2986683486],
[0.4832570738,       -0.3511084803,       -0.2986668445],
[0.0000018978,       -0.0000033480,       -0.6678431165],
[-0.0000017969,        0.0000009162,        1.3230014650],
[0.1871182835,       -0.5758942175,        0.9797717078],
[-0.4898861924,       -0.3559221410,       0.9797699802],
[-0.4898862039,        0.3559224872,        0.9797684555],
[0.1871182648,        0.5758945856,        0.9797692407],
[0.6055300485,        0.0000001908,        0.9797712507],
[0.7926501864,       -0.5758950093,        0.6055339635],
[0.3656681761,       -1.1254128670,        0.5916673591],
[-0.3027660545,       -0.9318173412,        0.6055326929],
[-0.9573332453,       -0.6955436707,        0.5916639831],
[-0.9797705418,       -0.0000006364,        0.6055294407],
[-0.9573332679,        0.6955423392,        0.5916610035],
[-0.3027660847,        0.9318160902,        0.6055287012],
[0.3656681396,        1.1254115783,        0.5916625380],
[0.7926501677,        0.5758937939,        0.6055314964],
[1.1833279992,       -0.0000006311,        0.5916664660],
[0.6770051458,       -0.9318186223,        0.0000033028],
[0.0000006771,       -1.1517907207,        0.0000025175],
[-0.6770037988,       -0.9318186442,        0.0000007900],
[-1.0954155825,       -0.3559242494,       -0.0000012200],
[-1.0954155940,        0.3559203788,       -0.0000027447],
[-0.6770038290,        0.9318147872,       -0.0000032017],
[0.0000006397,        1.1517868856,       -0.0000024165],
[0.6770051155,        0.9318148091,       -0.0000006889],
[1.0954168993,        0.3559204143,        0.0000013211],
[1.0954169108,       -0.3559242139,        0.0000028458],
[0.3027674014,       -0.9318199253,       -0.6055286002],
[-0.3656668229,       -1.1254154134,       -0.5916624370],
[-0.7926488510,       -0.5758976290,       -0.6055313954],
[-1.1833266824,       -0.0000032040,       -0.5916663649],
[-0.7926488697,        0.5758911742,       -0.6055338624],
[-0.3656668594,        1.1254090319,       -0.5916672580],
[0.3027673712,        0.9318135061,       -0.6055325919],
[0.9573345621,        0.6955398357,       -0.5916638820],
[0.9797718586,       -0.0000031986,       -0.6055293396],
[0.9573345846,       -0.6955461743,       -0.5916609025],
[-0.1871169480,       -0.5758984207,       -0.9797691397],
[-0.6055287318,       -0.0000040259,       -0.9797711497],
[-0.1871169667,        0.5758903824,       -0.9797716067],
[0.4898875091,        0.3559183059,       -0.9797698792],
[0.4898875207,       -0.3559263223,       -0.9797683545],
[0.0000031136,       -0.0000047513,       -1.3230013639]]*18.8973*0.36258

positions = [SVector{3}(p[i] for i in 1:3) for p in atoms]
dis2mat = get_distance2_mat(positions)
X = [ 1    1              0.001   0.000  11.338
 1    0              0.001   0.000  11.338
 1    1              0.020   0.000  11.338
 1    0              0.020   0.000  11.338
 1    1              0.035   0.000  11.338
 1    0              0.035   0.000  11.338
 1    1              0.100   0.000  11.338
 1    0              0.100   0.000  11.338
 1    1              0.400   0.000  11.338
 1    0              0.400   0.000  11.338]

radsymmvec = []

for row in eachrow(X)
    symmfunc = RadialType2{Float64}(row[3],row[5],[row[1],row[2]])
    push!(radsymmvec,symmfunc)
end

V = [[0.0001,1,1,11.338],[0.0001,-1,2,11.338],[0.003,-1,1,11.338],[0.003,-1,2,11.338],[0.008,-1,1,11.338],[0.008,-1,2,11.228],[0.008,1,2,11.338],[0.015,1,1,11.338],[0.015,-1,2,11.338],[0.015,-1,4,11.338],[0.015,-1,16,11.338],[0.025,-1,1,11.338],[0.025,1,1,11.338],[0.025,1,2,11.338],[0.025,-1,4,11.338],[0.025,-1,16,11.338],[0.025,1,16,11.338],[0.045,1,1,11.338],[0.045,-1,2,11.338],[0.045,-1,4,11.338],[0.045,1,4,11.338],[0.045,1,16,11.338],[0.08,1,1,11.338],[0.08,-1,2,11.338],[0.08,-1,4,11.338],[0.08,1,4,11.338]]

T = [[1.,1.,1.],[1.,1.,0.],[1.,0.,0.]]

angularsymmvec = []

for element in V 
    for types in T
        symmfunc = AngularType3{Float64}(element[1],element[2],element[3],11.338,types)
        push!(angularsymmvec,symmfunc)
    end
end

total_symm_vec = vcat(radsymmvec,angularsymmvec)

88-element Vector{Any}:
 RadialType2{Float64}(0.001, 11.338, [1.0, 1.0])
 RadialType2{Float64}(0.001, 11.338, [1.0, 0.0])
 RadialType2{Float64}(0.02, 11.338, [1.0, 1.0])
 RadialType2{Float64}(0.02, 11.338, [1.0, 0.0])
 RadialType2{Float64}(0.035, 11.338, [1.0, 1.0])
 RadialType2{Float64}(0.035, 11.338, [1.0, 0.0])
 RadialType2{Float64}(0.1, 11.338, [1.0, 1.0])
 RadialType2{Float64}(0.1, 11.338, [1.0, 0.0])
 RadialType2{Float64}(0.4, 11.338, [1.0, 1.0])
 RadialType2{Float64}(0.4, 11.338, [1.0, 0.0])
 ⋮
 AngularType3{Float64}(0.08, -1.0, 2.0, 11.338, [1.0, 1.0, 1.0], 0.5)
 AngularType3{Float64}(0.08, -1.0, 2.0, 11.338, [1.0, 1.0, 0.0], 0.5)
 AngularType3{Float64}(0.08, -1.0, 2.0, 11.338, [1.0, 0.0, 0.0], 0.5)
 AngularType3{Float64}(0.08, -1.0, 4.0, 11.338, [1.0, 1.0, 1.0], 0.125)
 AngularType3{Float64}(0.08, -1.0, 4.0, 11.338, [1.0, 1.0, 0.0], 0.125)
 AngularType3{Float64}(0.08, -1.0, 4.0, 11.338, [1.0, 0.0, 0.0], 0.125)
 AngularType3{Float64}(0.08, 1.0, 4.0, 11.338, [1.0, 1.0, 1.0], 0.1

Ready to start workshopping:

Considering the cutoff radius of every symmetry function is identical, we can calculate an f_cut matrix. 

In [3]:
f_mat = cutoff_function.(sqrt.(dis2mat),Ref(total_symm_vec[1].r_cut))

55×55 Matrix{Float64}:
 1.0        0.649134    0.649134    …  0.21115     0.21115     0.0959383
 0.649134   1.0         0.617699       0.0         0.0         0.0
 0.649134   0.617699    1.0            0.00208061  0.0912928   0.0
 0.649134   0.617699    0.617699       0.0         0.00208061  0.0
 0.649134   0.617699    0.223352       0.00208061  0.0         0.0
 0.649134   0.617699    0.223352    …  0.0912928   0.00208061  0.0
 0.649134   0.617699    0.617699       0.0912928   0.0912928   0.0
 0.649134   0.223352    0.617699       0.0912928   0.355548    0.185434
 0.649134   0.223352    0.223352       0.0912928   0.0912928   0.185434
 0.649134   0.223352    0.0889637      0.355548    0.0912928   0.185434
 ⋮                                  ⋱                          
 0.0959383  0.0         0.0            0.623382    0.164805    0.0613471
 0.21115    0.00208061  0.0912928      0.608792    0.608792    0.164805
 0.0959383  0.0         0.185434       0.164805    0.623382    0.0613471
 0.2

In [4]:
@everywhere calc_one_symm_val(r2_ij,fc_ij,eta) = ifelse(fc_ij!=0. && fc_ij!=1., fc_ij*exp(-eta*r2_ij), 0.)

@everywhere function calc_symm_function(positions,dist2_matrix,fc_matrix,index,symmfunc::RadialType2)
    
    eta=symmfunc.eta
    g_vec = calc_one_symm_val.(dist2_matrix[:,index],fc_matrix[:,index],eta)
    return sum(g_vec)
end


In [5]:
@everywhere function calc_one_symm_val(position1,position2,position3,r2_ij,r2_ik,r2_jk,f_ij,f_ik,f_jk,η,λ,ζ)
        θ = angular_measure(position1,position2,position3,r2_ij,r2_ik)
    
        g= (1+λ*θ)^ζ * exp(-η*(r2_ij+r2_ik+r2_jk)) * f_ij * f_ik * f_jk
        
    return g
end

@everywhere function calc_symm_function(positions,dis2_mat,fc_mat,index,symmfunc::AngularType3)
    N = length(positions)
    g = 0.
    η,λ,ζ = symmfunc.eta,symmfunc.lambda,symmfunc.zeta
    if symmfunc.type_vec == [1.,1.,1.]
        for j=(1:N)
            if j != index
                for k  = (1:j-1)
                    if k!= index
                        g+= calc_one_symm_val(
                            positions[index],positions[j],positions[k],dis2_mat[index,j],dis2_mat[index,k],dis2_mat[j,k],fc_mat[index,j],fc_mat[index,k],fc_mat[j,k] ,η,λ,ζ
                            ) 
                    end            
                end
            end
        end
    end

    return symmfunc.tpz*g
end

In [6]:
function symm_functions(positions,dis2_mat,fc_mat,index,symm_func_vec)
    G_vec = calc_symm_function.(Ref(positions),Ref(dis2_mat),Ref(fc_mat),Ref(index),symm_func_vec)
    return G_vec
end
@benchmark symm_functions($positions,$dis2mat,$f_mat,rand(1:55),$total_symm_vec)

BenchmarkTools.Trial: 5428 samples with 1 evaluation.
 Range (min … max):  886.096 μs …  2.678 ms  ┊ GC (min … max): 0.00% … 65.36%
 Time  (median):     924.061 μs              ┊ GC (median):    0.00%
 Time  (mean ± σ):   920.368 μs ± 36.641 μs  ┊ GC (mean ± σ):  0.07% ±  1.24%

                      ▁▁             █▄ ▁                       
  ▂▂▂▄▄▃▃▂▂▂▂▂▂▂▂▂▂▅▆▆██▆▅▄▄▃▄▄▃▃▃▃▃███▇█▅▅▄▃▃▃▃▃▂▂▂▂▂▂▃▃▂▂▂▁▁ ▃
  886 μs          Histogram: frequency by time          953 μs <

 Memory estimate: 23.25 KiB, allocs estimate: 209.

In [7]:
@benchmark calc_symm_function($positions,$dis2mat,$f_mat,rand(1:55),$total_symm_vec[11])

BenchmarkTools.Trial: 10000 samples with 1 evaluation.
 Range (min … max):  31.239 μs …  57.219 μs  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     32.024 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   32.059 μs ± 584.578 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

  ▃▄▅▅▄▂          ▂▇▇█▇▆▅▂          ▂▃▃▃▃▂▁                    ▂
  ██████▇▅▄▄▄▂▄▄▃▄█████████▇▇▆▆▆▇▆▆▇███████▇██▇▇▇▇▇▇▆▇▇▇▇▆▆▇▆▆ █
  31.2 μs       Histogram: log(frequency) by time      33.6 μs <

 Memory estimate: 96 bytes, allocs estimate: 2.

In [8]:
@benchmark calc_symmetry_function($positions,$dis2mat,rand(1:55),$total_symm_vec[11])

BenchmarkTools.Trial: 10000 samples with 1 evaluation.
 Range (min … max):  21.627 μs … 846.359 μs  ┊ GC (min … max): 0.00% … 94.40%
 Time  (median):     27.104 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   28.510 μs ±  16.823 μs  ┊ GC (mean ± σ):  1.25% ±  2.11%

               ▁▅█▇▇▃                                           
  ▂▅██▇▅▃▁▁▁▂▂▄██████▇▄▂▂▂▂▃▃▄▅▇▇█▇▆▄▄▃▂▂▂▂▂▂▃▃▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁ ▃
  21.6 μs         Histogram: frequency by time         40.4 μs <

 Memory estimate: 23.39 KiB, allocs estimate: 4.

More important here is to gauge how slow it is to calculate the total symmetry vector for each atom

In [9]:
@everywhere function total_total_symm(positions,dis2_mat,fc_mat,symm_func_vec)
    g_tot=[]
    for index in eachindex(positions)
        G_vec = symm_functions(positions,dis2mat,f_mat,rand(1:55),total_symm_vec)
        push!(g_tot,G_vec)
    end
    return g_tot
end
@benchmark total_total_symm($positions,$dis2mat,$f_mat,$total_symm_vec)

BenchmarkTools.Trial: 100 samples with 1 evaluation.
 Range (min … max):  49.555 ms …  52.960 ms  ┊ GC (min … max): 0.00% … 3.57%
 Time  (median):     50.059 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):   50.216 ms ± 565.401 μs  ┊ GC (mean ± σ):  0.08% ± 0.50%

    █▂  ▅▅  ▅      ▂                                            
  █▇██▅███▄███▄█▄▄▅█▅▅█▄▅▅▁▄▇█▄▁▅▄▁▅▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▄ ▄
  49.6 ms         Histogram: frequency by time         52.5 ms <

 Memory estimate: 1.25 MiB, allocs estimate: 11499.

In [10]:
total_total_symm(positions,dis2mat,f_mat,total_symm_vec)

55-element Vector{Any}:
 [11.966607068035858, 11.966607068035858, 6.362235447320308, 6.362235447320308, 4.143106864843472, 4.143106864843472, 0.8571680648473241, 0.8571680648473241, 0.0011760266346499328, 0.0011760266346499328  …  0.0, 0.0050020475206395435, 0.0, 0.0, 0.0005983507133783634, 0.0, 0.0, 0.021924952318636424, 0.0, 0.0]
 [7.455371452718601, 7.455371452718601, 3.928878422174356, 3.928878422174356, 2.5459605422090656, 2.5459605422090656, 0.5083986415121435, 0.5083986415121435, 0.0005285363553477341, 0.0005285363553477341  …  0.0, 0.0019216479937513502, 0.0, 0.0, 0.00018203623944911722, 0.0, 0.0, 0.010500880314053876, 0.0, 0.0]
 [5.699536974721713, 5.699536974721713, 2.9415593756155047, 2.9415593756155047, 1.9155542685388358, 1.9155542685388358, 0.41077108425551817, 0.41077108425551817, 0.0005573982216284726, 0.0005573982216284726  …  0.0, 0.0016597483675882027, 0.0, 0.0, 0.00013714023980748437, 0.0, 0.0, 0.007651868025700858, 0.0, 0.0]
 [7.4553714533080715, 7.4553714533080715

# Stating the obvious

There are two components to this: firstly, it may be faster to implicitly remove the double calculation of triples by assigning them immediately. That is, go over symmetry functions rather than atoms and assign as we go, reducing the calculation from $55\times \sum_{j=1}^{54} j $ to $\sum_{i=1}^{55} \sum_{j=i+1}^{55}j $ This reduces the time of total calculation, but not by enough. We can further speed this up by working on the calculation of the symmetry function itself: this may require more thought. 

In [11]:
@everywhere function calc_symm_vals!(positions,dist2_mat,f_mat,g_vec,symm_func::RadialType2)
    N=length(g_vec)
    if symm_func.type_vec == [1.,1.]
        
        for atomindex in eachindex(g_vec)
            for index2 in (atomindex+1):N
                g_val =  calc_one_symm_val(dist2_mat[atomindex,index2],f_mat[atomindex,index2],symm_func.eta)
                g_vec[atomindex] +=g_val 
                g_vec[index2] += g_val
            end
        end
    else
        g_vec = zeros(N)
    end

    return g_vec
end

@everywhere function update_g_vals!(g_vec,g_val,index1,index2,index3)
    g_vec[index1] += g_val
    g_vec[index2] += g_val
    g_vec[index3] += g_val

    return g_vec
end

@everywhere function calc_symm_vals!(positions,dist2_mat,f_mat,g_vec,symm_func::AngularType3)
    N = length(g_vec)
    η,λ,ζ = symm_func.eta,symm_func.lambda,symm_func.zeta
    if symm_func.type_vec == [1.,1.,1.]
        for atomindex in eachindex(g_vec)
            for index2 in (atomindex+1):N
                for index3 in (index2+1):N

                    g_val=calc_one_symm_val(positions[atomindex],positions[index2],positions[index3],dist2_mat[atomindex,index2],dist2_mat[atomindex,index3],dist2_mat[index2,index3],f_mat[atomindex,index2],f_mat[atomindex,index3],f_mat[index2,index3],η,λ,ζ)

                    update_g_vals!(g_vec,g_val,atomindex,index2,index3)
                    # g_vec[atomindex] += g_val
                    # g_vec[index2] += g_val
                    # g_vec[index3] += g_val
                end
            end
        end
    else
        g_vec = zeros(N)
    end


    return symm_func.tpz*g_vec
end

In [12]:
@everywhere function init_symm_vecs(dist2_mat,total_symm_vec)
    g_mat=zeros(length(total_symm_vec),size(dist2_mat)[1])
    return g_mat 
end


function total_symm_calc(positions,dist2_mat,f_mat,total_symm_vec)
    g_mat = init_symm_vecs(dist2_mat,total_symm_vec)
    for g_index in eachindex(total_symm_vec)
        g_mat[g_index,:] = calc_symm_vals!(positions,dist2_mat,f_mat,g_mat[g_index,:],total_symm_vec[g_index])
    end
    
    return g_mat
end

total_symm_calc (generic function with 1 method)

In [13]:
gvec = zeros(55)
@benchmark calc_symm_vals!($positions,$dis2mat,$f_mat,$gvec,$total_symm_vec[11])

BenchmarkTools.Trial: 8208 samples with 1 evaluation.
 Range (min … max):  585.268 μs … 641.945 μs  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     611.563 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   608.388 μs ±  10.711 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%

                     ▁▄▃▁             ▂███▄▄▁                    
  ▁▃▄▆▅▆▄▅▅▃▃▃▃▂▂▂▂▃▆████▇▇▆▆▅▄▄▄▃▄▃▄▇███████▇▅▆▄▄▄▄▃▃▃▃▃▄▃▃▃▂▂ ▄
  585 μs           Histogram: frequency by time          630 μs <

 Memory estimate: 576 bytes, allocs estimate: 2.

In [14]:
gmat = total_symm_calc(positions,dis2mat,f_mat,total_symm_vec)

88×55 Matrix{Float64}:
 14.6407       11.9666       11.9666       …  7.45537      5.69954
  0.0           0.0           0.0             0.0          0.0
  7.16978       6.36224       6.36224         3.92888      2.94156
  0.0           0.0           0.0             0.0          0.0
  4.52421       4.14311       4.14311         2.54596      1.91555
  0.0           0.0           0.0          …  0.0          0.0
  0.972533      0.857168      0.857168        0.508399     0.410771
  0.0           0.0           0.0             0.0          0.0
  0.00179489    0.00117603    0.00117603      0.000528536  0.000557398
  0.0           0.0           0.0             0.0          0.0
  ⋮                                        ⋱               
  0.00742548    0.00531799    0.00531799      0.00203029   0.00164947
  0.0           0.0           0.0          …  0.0          0.0
  0.0           0.0           0.0             0.0          0.0
  0.000947854   0.000650384   0.000650384     0.000176168  0.00011

In [15]:
@benchmark total_symm_calc($positions,$dis2mat,$f_mat,$total_symm_vec)

BenchmarkTools.Trial: 290 samples with 1 evaluation.
 Range (min … max):  16.928 ms …  18.474 ms  ┊ GC (min … max): 0.00% … 5.26%
 Time  (median):     17.276 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):   17.264 ms ± 183.098 μs  ┊ GC (mean ± σ):  0.02% ± 0.31%

           ▂▁▂▄▂▄▃ █▁      ▃   ▂▁▆▄▂▇ ▃▂     ▆   ▂ ▁▄▁          
  ▃▁▄▆▆█▃▆▇██████████▃█▇▄▄██▄▇██████████▇▄▇▇▇██▇▄█▇███▆▄▁▁▃▄▃▃ ▄
  16.9 ms         Histogram: frequency by time         17.6 ms <

 Memory estimate: 154.12 KiB, allocs estimate: 401.

In [16]:
@everywhere function calc_symm_vals!(positions,new_pos,new_dis_vec,new_f_vec,atomindex,dist2_mat,f_mat,g_vec,symm_func::RadialType2)

    N = length(g_vec)
    if symm_func.type_vec == [1., 1.]
        for index2 in 1:N
            if index2 != atomindex
                delta_val = calc_one_symm_val(new_dis_vec[index2],new_f_vec[index2],symm_func.eta) - calc_one_symm_val(dist2_mat[index2,atomindex],f_mat[index2,atomindex],symm_func.eta)

                g_vec[atomindex] +=delta_val 
                g_vec[index2] += delta_val
            else
                g_vec = zeros(N)
            end
        end
    else
        g_vec = zeros(N)
    end

        return g_vec
end

@everywhere function calc_symm_vals!(positions,new_pos,new_dis_vec,new_f_vec,atomindex,dist2_mat,f_mat,g_vec,symm_func::AngularType3)

    N = length(g_vec)
    η,λ,ζ = symm_func.eta,symm_func.lambda,symm_func.zeta
    if symm_func.type_vec == [1.,1.,1.]
        for index2 = 1:N
            if index2 != atomindex
                for index3=index2+1:N
                    if index3 != atomindex

                        delta_val = calc_one_symm_val(new_pos,positions[index2],positions[index3],new_dis_vec[index2],new_dis_vec[index3],dist2_mat[index2,index3],new_f_vec[index2],new_f_vec[index3],f_mat[index2,index3],η,λ,ζ) - calc_one_symm_val(positions[atomindex],positions[index2],positions[index3],dist2_mat[atomindex,index2],dist2_mat[atomindex,index3],dist2_mat[index2,index3],f_mat[atomindex,index2],f_mat[atomindex,index3],f_mat[index2,index3],η,λ,ζ)

                        update_g_vals!(g_vec,delta_val,atomindex,index2,index3)
                    end
                end
            end
        end
    else
        g_vec = zeros(N)
    end

    return symm_func.tpz*g_vec
end

In [17]:
@everywhere function total_symm_calc(positions,new_pos,dist2_mat,new_dist_vec,f_mat,new_f_vec,g_mat,atomindex,total_symm_vec)
    for g_index in eachindex(total_symm_vec)
        g_mat[g_index,:] = calc_symm_vals!(positions,new_pos,new_dist_vec,new_f_vec,atomindex,dist2_mat,f_mat,g_mat[g_index,:],total_symm_vec[g_index])
    end

    return g_mat
end

In [18]:
delta_r = [0.1,-0.2,0.1]
new_pos = positions[3]+delta_r
new_dist_vec = [distance2(new_pos,b) for b in positions]
new_f_vec = cutoff_function.(sqrt.(new_dist_vec),Ref(total_symm_vec[1].r_cut))
@benchmark calc_symm_vals!($positions,$new_pos,$new_dist_vec,$new_f_vec,$3,$dis2mat,$f_mat,$zeros(55),$angularsymmvec[1])


BenchmarkTools.Trial: 10000 samples with 1 evaluation.
 Range (min … max):  59.119 μs … 80.208 μs  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     62.038 μs              ┊ GC (median):    0.00%
 Time  (mean ± σ):   61.780 μs ±  1.363 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%

    ▂▇▂    ▁▃▂   ▂▇▃    ▃▄▃▁▁▁▁██▂   ▁▅▅▃▂▁▂▂▄▅▁  ▁▁▁▂▁       ▂
  ▃▃███▆▁▄▅████▇█████▇█▇████████████████████████████████▇▆▇▇▇ █
  59.1 μs      Histogram: log(frequency) by time      64.9 μs <

 Memory estimate: 1.08 KiB, allocs estimate: 4.

In [19]:
g_mat = total_symm_calc(positions,dis2mat,f_mat,total_symm_vec)

@benchmark total_symm_calc($positions,$new_pos,$dis2mat,$new_dist_vec,$f_mat,$new_f_vec,$g_mat,$3,$total_symm_vec)

BenchmarkTools.Trial: 2822 samples with 1 evaluation.
 Range (min … max):  1.695 ms …  2.933 ms  ┊ GC (min … max): 0.00% … 39.23%
 Time  (median):     1.769 ms              ┊ GC (median):    0.00%
 Time  (mean ± σ):   1.771 ms ± 59.949 μs  ┊ GC (mean ± σ):  0.15% ±  1.88%

                                █                             
  ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▂▃▂▃▂▂▂▂▃▂▂▂▂▂▂▅█▄▃▃▃▂▂▂▃▃▃▂▂▂▂▂▁▂▁▁▁▁▁▁▁▁▁▁ ▂
  1.69 ms        Histogram: frequency by time        1.84 ms <

 Memory estimate: 121.44 KiB, allocs estimate: 492.

In [20]:
# vec = map( calc_symm_vals!,Ref(positions),Ref(new_pos),Ref(new_dist_vec),Ref(new_f_vec),Ref(3),Ref(dis2mat),Ref(f_mat), eachrow(g_mat) , total_symm_vec )


g_mat = total_symm_calc(positions,dis2mat,f_mat,total_symm_vec)

vec = map((gvector,symmfuncs) -> calc_symm_vals!(positions,new_pos,new_dist_vec,new_f_vec,3,dis2mat,f_mat, gvector , symmfuncs ) ,eachrow(g_mat),total_symm_vec  )

g_mat = total_symm_calc(positions,dis2mat,f_mat,total_symm_vec)

vec2 = pmap((gvector,symmfuncs) -> calc_symm_vals!(positions,new_pos,new_dist_vec,new_f_vec,3,dis2mat,f_mat, gvector , symmfuncs ) ,eachrow(g_mat),total_symm_vec  )

g_mat = total_symm_calc(positions,dis2mat,f_mat,total_symm_vec)

xvec = calc_symm_vals!.(Ref(positions),Ref(new_pos),Ref(new_dist_vec),Ref(new_f_vec),Ref(3),Ref(dis2mat),Ref(f_mat), eachrow(g_mat) , total_symm_vec)

88-element Vector{Vector{Float64}}:
 [0.0, 0.0, -0.2190537307241303, -0.022132771780947413, -0.02418285886968563, -0.02204166861876014, -0.014884211021116589, -0.01954729827461066, -0.02426680395979866, -0.017021815753457445  …  0.0, 0.0, -0.007073538261540488, 0.0008184984536820372, -0.009138205270856514, -0.0015615253964638264, 0.0, -0.0014495225056633419, -0.007885005864590025, 0.0]
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
 [0.0, 0.0, -0.051458625503653856, -0.025262912170049334, -0.011423785225819563, -0.010450321135117402, -0.017087187112375224, -0.022357650986468136, -0.011461799283959143, -0.004547399528379242  …  0.0, 0.0, -0.001977624726511088, 0.00035482760707045147, -0.002538594854819007, -0.0001584316781119373, 0.0, -0.00014777706150619, -0.0021989818098522938, 0.0]
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
 [0.0, 0.0, 0.004683069984775188, -0.02382

In [21]:
@everywhere function parversion(positions,new_pos,dist2_mat,new_dist_vec,f_mat,new_f_vec,g_mat,atomindex,total_symm_vec)

    delta_mat = pmap((gvector,symmfuncs) -> calc_symm_vals!(positions,new_pos,new_dist_vec,new_f_vec,3,dis2mat,f_mat, gvector , symmfuncs ) ,eachrow(g_mat),total_symm_vec  )

    return delta_mat

end
g_mat = total_symm_calc(positions,dis2mat,f_mat,total_symm_vec)
parversion(positions,new_pos,dis2mat,new_dist_vec,f_mat,new_f_vec,g_mat,3,total_symm_vec)

88-element Vector{Vector{Float64}}:
 [0.0, 0.0, -0.2190537307241303, -0.022132771780947413, -0.02418285886968563, -0.02204166861876014, -0.014884211021116589, -0.01954729827461066, -0.02426680395979866, -0.017021815753457445  …  0.0, 0.0, -0.007073538261540488, 0.0008184984536820372, -0.009138205270856514, -0.0015615253964638264, 0.0, -0.0014495225056633419, -0.007885005864590025, 0.0]
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
 [0.0, 0.0, -0.051458625503653856, -0.025262912170049334, -0.011423785225819563, -0.010450321135117402, -0.017087187112375224, -0.022357650986468136, -0.011461799283959143, -0.004547399528379242  …  0.0, 0.0, -0.001977624726511088, 0.00035482760707045147, -0.002538594854819007, -0.0001584316781119373, 0.0, -0.00014777706150619, -0.0021989818098522938, 0.0]
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
 [0.0, 0.0, 0.004683069984775188, -0.02382

In [22]:
@benchmark parversion($positions,$new_pos,$dis2mat,$new_dist_vec,$f_mat,$new_f_vec,$g_mat,$3,$total_symm_vec)

BenchmarkTools.Trial: 2639 samples with 1 evaluation.
 Range (min … max):  1.801 ms …   4.096 ms  ┊ GC (min … max): 0.00% … 52.35%
 Time  (median):     1.883 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):   1.894 ms ± 124.985 μs  ┊ GC (mean ± σ):  0.37% ±  3.02%

                               █▂                              
  ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▂▂▃▄▃▂▃▂▃▂▂▂▃▂▃██▇▇▄▄▅▄▄▅▃▄▃▃▃▃▄▃▃▂▂▂▂▂▂▁▁▁▁▁ ▂
  1.8 ms          Histogram: frequency by time        1.95 ms <

 Memory estimate: 155.20 KiB, allocs estimate: 1356.

In [23]:
@everywhere function threadversion(positions,new_pos,dist2_mat,new_dist_vec,f_mat,new_f_vec,g_mat,atomindex,total_symm_vec)
    Threads.@threads for g_index in eachindex(total_symm_vec)
        g_mat[g_index,:] = calc_symm_vals!(positions,new_pos,new_dist_vec,new_f_vec,atomindex,dist2_mat,f_mat,g_mat[g_index,:],total_symm_vec[g_index])
    end
    return g_mat
end

In [24]:
threadversion(positions,new_pos,dis2mat,new_dist_vec,f_mat,new_f_vec,g_mat,3,total_symm_vec)

88×55 Matrix{Float64}:
  0.0        0.0        -0.219054     …  -0.00788501   0.0
  0.0        0.0         0.0              0.0          0.0
  0.0        0.0        -0.0514586       -0.00219898   0.0
  0.0        0.0         0.0              0.0          0.0
  0.0        0.0         0.00468307      -0.000757458  0.0
  0.0        0.0         0.0          …   0.0          0.0
  0.0        0.0         0.0350579       -5.65521e-6   0.0
  0.0        0.0         0.0              0.0          0.0
  0.0        0.0         0.000474419     -1.8752e-16   0.0
  0.0        0.0         0.0              0.0          0.0
  ⋮                                   ⋱                
 -1.84708   -0.878052    1.97071          0.000991639  0.000824737
  0.0        0.0         0.0          …   0.0          0.0
  0.0        0.0         0.0              0.0          0.0
 -0.186152  -0.0873587   0.303967         2.09925e-5   1.42341e-5
  0.0        0.0         0.0              0.0          0.0
  0.0        0.0     

In [25]:
@benchmark threadversion($positions,$new_pos,$dis2mat,$new_dist_vec,$f_mat,$new_f_vec,$g_mat,$3,$total_symm_vec)

BenchmarkTools.Trial: 8687 samples with 1 evaluation.
 Range (min … max):  302.870 μs …  50.073 ms  ┊ GC (min … max): 0.00% … 98.53%
 Time  (median):     447.135 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   573.054 μs ± 826.503 μs  ┊ GC (mean ± σ):  2.81% ±  2.11%

  █ █▇▇▇▂▄▂                                                      
  █▃████████▆▅▄▃▃▃▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▂▂▂▁▂▁▁▂▁▁▁▂▁▁▁▁▁▁▁ ▃
  303 μs           Histogram: frequency by time          1.6 ms <

 Memory estimate: 126.17 KiB, allocs estimate: 541.

In [26]:
@everywhere function testingtime(positions,new_pos,dist2_mat,new_dist_vec,f_mat,new_f_vec,g_mat,atomindex,total_symm_vec)
    newmat = copy(g_mat)
    for j = 1:1000
        newmat = threadversion(positions,new_pos,dist2_mat,new_dist_vec,f_mat,new_f_vec,g_mat,atomindex,total_symm_vec)
    end
    return newmat
end
@benchmark testingtime($positions,$new_pos,$dis2mat,$new_dist_vec,$f_mat,$new_f_vec,$g_mat,$3,$total_symm_vec)

BenchmarkTools.Trial: 9 samples with 1 evaluation.
 Range (min … max):  479.593 ms … 694.839 ms  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     569.631 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):   571.593 ms ±  62.629 ms  ┊ GC (mean ± σ):  2.44% ± 2.93%

  █       █        █  █    █   █  █      █                    █  
  █▁▁▁▁▁▁▁█▁▁▁▁▁▁▁▁█▁▁█▁▁▁▁█▁▁▁█▁▁█▁▁▁▁▁▁█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█ ▁
  480 ms           Histogram: frequency by time          695 ms <

 Memory estimate: 123.31 MiB, allocs estimate: 542957.